[workspace]
resolver = "2"
members = ["program", "clients/rust"]

[workspace.metadata.cli]
solana = "2.1.9"

# Specify Rust toolchains for rustfmt, clippy, and build.
# Any unprovided toolchains default to stable.
[workspace.metadata.toolchains]
format = "1.81.0"
lint = "1.81.0"
